import * as vscode from "vscode";
import { readdir, rm } from "node:fs/promises";
import {
  clearCredentials,
  clearPassword,
  clearUsername,
  normalizeBaseUrlInput,
  normalizeSecretInput,
  readStoredUsername,
  storePassword,
  storeUsername
} from "../config/resolveConfig";
import { JsonlLogger } from "../logging/jsonlLogger";
import { KiwiFileSystemProvider } from "../provider/KiwiFileSystemProvider";
import { KiwiPlansTreeDataProvider } from "./KiwiPlansTreeDataProvider";

export function registerConfigRuntimeCommands(args: {
  context: vscode.ExtensionContext;
  provider: KiwiFileSystemProvider;
  treeDataProvider: KiwiPlansTreeDataProvider;
  logger: JsonlLogger;
  isDebugF5Runtime: () => boolean;
}): vscode.Disposable[] {
  const { context, provider, treeDataProvider, logger, isDebugF5Runtime } = args;

  return [
    vscode.commands.registerCommand("kiwi.openRoot", async () => {
      provider.refreshListings();
      treeDataProvider.refresh();
      await vscode.commands.executeCommand("workbench.view.explorer");
      try {
        await vscode.commands.executeCommand("kiwiPlans.focus");
      } catch {
        // The view focus command is generated by VS Code at runtime.
      }
      return "kiwiPlans";
    }),
    vscode.commands.registerCommand("kiwi.configureBaseUrl", async (injectedInput?: string) => {
      const configuration = vscode.workspace.getConfiguration("kiwi");
      const input =
        injectedInput ??
        (await vscode.window.showInputBox({
          placeHolder: "https://kiwi.example.com/",
          prompt: "接続先の Kiwi base URL を入力してください",
          title: "Kiwi: ベース URL を設定",
          value: configuration.get<string>("baseUrl") ?? ""
        }));
      if (input === undefined) {
        return undefined;
      }
      const normalized = normalizeBaseUrlInput(input);
      if (!normalized) {
        void vscode.window.showErrorMessage(
          "Kiwi base URL には http:// または https:// の URL を入力してください。"
        );
        return undefined;
      }
      await configuration.update("baseUrl", normalized, vscode.ConfigurationTarget.Global);
      void vscode.window.showInformationMessage("Kiwi base URL を更新しました。");
      return normalized;
    }),
    vscode.commands.registerCommand("kiwi.configureUsername", async (injectedInput?: string) => {
      const input =
        injectedInput ??
        (await vscode.window.showInputBox({
          placeHolder: "admin",
          prompt: "Kiwi ユーザ名を入力してください",
          title: "Kiwi: ユーザー名を設定",
          value: (await readStoredUsername(context)) ?? ""
        }));
      if (input === undefined) {
        return undefined;
      }
      const normalized = normalizeSecretInput(input);
      if (!normalized) {
        void vscode.window.showErrorMessage("Kiwi ユーザ名は空にできません。");
        return undefined;
      }
      await storeUsername(context, normalized);
      void vscode.window.showInformationMessage("Kiwi ユーザ名を保存しました。");
      return normalized;
    }),
    vscode.commands.registerCommand("kiwi.configurePassword", async (injectedInput?: string) => {
      const input =
        injectedInput ??
        (await vscode.window.showInputBox({
          password: true,
          placeHolder: "Paste password",
          prompt: "Kiwi パスワードを入力してください",
          title: "Kiwi: パスワードを設定"
        }));
      if (input === undefined) {
        return undefined;
      }
      const normalized = normalizeSecretInput(input);
      if (!normalized) {
        void vscode.window.showErrorMessage("Kiwi パスワードは空にできません。");
        return undefined;
      }
      await storePassword(context, normalized);
      void vscode.window.showInformationMessage("Kiwi パスワードを保存しました。");
      return normalized;
    }),
    vscode.commands.registerCommand("kiwi.clearBaseUrl", async (confirmed?: boolean) => {
      const proceed =
        confirmed === true ||
        (await vscode.window.showWarningMessage(
          "Base URL をクリアしますか？",
          { modal: true },
          "クリア"
        )) === "クリア";
      if (!proceed) {
        return false;
      }
      await vscode.workspace
        .getConfiguration("kiwi")
        .update("baseUrl", "", vscode.ConfigurationTarget.Global);
      provider.refreshListings();
      treeDataProvider.refresh();
      void vscode.window.showInformationMessage("Kiwi base URL をクリアしました。");
      return true;
    }),
    vscode.commands.registerCommand("kiwi.clearUsername", async (confirmed?: boolean) => {
      const proceed =
        confirmed === true ||
        (await vscode.window.showWarningMessage(
          "ユーザ名をクリアしますか？",
          { modal: true },
          "クリア"
        )) === "クリア";
      if (!proceed) {
        return false;
      }
      await clearUsername(context);
      void vscode.window.showInformationMessage("Kiwi ユーザ名をクリアしました。");
      return true;
    }),
    vscode.commands.registerCommand("kiwi.clearPassword", async (confirmed?: boolean) => {
      const proceed =
        confirmed === true ||
        (await vscode.window.showWarningMessage(
          "パスワードをクリアしますか？",
          { modal: true },
          "クリア"
        )) === "クリア";
      if (!proceed) {
        return false;
      }
      await clearPassword(context);
      void vscode.window.showInformationMessage("Kiwi パスワードをクリアしました。");
      return true;
    }),
    vscode.commands.registerCommand("kiwi.clearConfiguration", async (confirmed?: boolean) => {
      const proceed =
        confirmed === true ||
        (await vscode.window.showWarningMessage(
          "Kiwi の接続設定をすべてクリアしますか？",
          { modal: true },
          "クリア"
        )) === "クリア";
      if (!proceed) {
        return false;
      }
      await vscode.workspace
        .getConfiguration("kiwi")
        .update("baseUrl", "", vscode.ConfigurationTarget.Global);
      await clearCredentials(context);
      provider.refreshListings();
      treeDataProvider.refresh();
      void vscode.window.showInformationMessage("Kiwi 接続設定をすべてクリアしました。");
      return true;
    }),
    vscode.commands.registerCommand("kiwi.openTreeItem", async (uri?: vscode.Uri) => {
      if (!uri) {
        return;
      }
      await vscode.commands.executeCommand("vscode.open", uri);
    }),
    vscode.commands.registerCommand("kiwi.refreshPlans", async () => {
      provider.refreshListings();
      treeDataProvider.refresh();
      return "kiwiPlans";
    }),
    vscode.commands.registerCommand("kiwi.clearRuntimeLogs", async () => {
      if (!isDebugF5Runtime()) {
        void vscode.window.showInformationMessage("Runtime logs are available only in debug-f5 mode.");
        return 0;
      }

      const directory = logger.getResolvedRuntimeLogDirectory();
      if (!directory) {
        void vscode.window.showInformationMessage("Runtime log path is not resolved yet.");
        return 0;
      }

      let removed = 0;
      try {
        const entries = await readdir(directory, { withFileTypes: true });
        for (const entry of entries) {
          if (entry.isFile() && entry.name.endsWith(".jsonl")) {
            await rm(vscode.Uri.joinPath(vscode.Uri.file(directory), entry.name).fsPath, {
              force: true
            });
            removed += 1;
          }
        }
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
          throw error;
        }
      }

      logger.resetRuntimeLogState();
      void vscode.window.showInformationMessage(`Removed ${removed} runtime log file(s).`);
      return removed;
    }),
    vscode.commands.registerCommand("kiwi.revealRuntimeLogs", async () => {
      if (!isDebugF5Runtime()) {
        void vscode.window.showInformationMessage("Runtime logs are available only in debug-f5 mode.");
        return;
      }

      const directory = logger.getResolvedRuntimeLogDirectory();
      if (!directory) {
        void vscode.window.showInformationMessage("Runtime log path is not resolved yet.");
        return;
      }

      await vscode.env.openExternal(vscode.Uri.file(directory));
      return directory;
    })
  ];
}
